# matplotlib for graphing utility
import matplotlib as plt

# 1) import data from results.csv generated by the main java program

# 2) create line graphs for each of the following results

# LINE GRAPHS FOR DATA SETS OF 100 -> 100,000 #
# Loading Sales Data Graph
# Retrieve the latest sale graph
# Compute the total revenue graph
# Check for duplicate sale IDs graph
# Search for a sale by its ID graph

# 3) Save resulting graph to png for reflection document
